name: app_gestion_negocio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  path: ^1.8.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  archive: ^3.6.1
  uuid: ^4.5.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Regular.ttf
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf
    - family: Faustina
      fonts:
        - asset: assets/fonts/Faustina-Regular.ttf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: MeowScript
      fonts:
        - asset: assets/fonts/MeowScript-Regular.ttf
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy-Regular.ttf
    - family: Tangerine
      fonts:
        - asset: assets/fonts/Tangerine-Regular.ttf
  assets:
    - assets/fonts/